### ISSUE TITLE
[Bug]: Skipping update version option doesn't work

### ISSUE THREAD

**Issue by Metazolid** [DmitriySalnikov/OBSNotifier#12]
### Commit or version

1.2.1

### On which operating systems the error occurs

Windows

### Issue description

![image](https://github.com/DmitriySalnikov/OBSNotifier/assets/17498384/75ef4a72-1b38-4abc-b6df-7b1a34c6330c)

I get asked after every reboot if I want to update, even if I pick the option that lets me skip the version.

### Steps to reproduce

Get the update prompt, then select "No" and restart the computer.

**Comment by DmitriySalnikov** [comment]
`SkipVersion` is part of the settings you had problems with here #10

I can't reproduce the same behavior.
The only similar thing I can do is open the settings folder and delete the `settings.json` file there. Maybe you have some kind of antivirus doing this? (please reply in #10)
