### ISSUE TITLE
[Feature request] Screenshot notifications

### ISSUE THREAD

**Issue by KyroOW** [DmitriySalnikov/OBSNotifier#2]
I checked all notifications that OBS Notifier can provide but i didn't find notifications for screenshots, it's the only notification missing and it would be great to add it

**Comment by DmitriySalnikov** [comment]
At the moment, obs notifier uses obs-websocket 4.9.1 in which there are no events about saving replays or saving screenshots. Check out the `Events` section here https://github.com/obsproject/obs-websocket/blob/4.x-compat/docs/generated/protocol.md#table-of-contents

Now I am very close to releasing an update to obs-websocket 5.x, but in its documentation I also do not find anything related to the event about saving screenshots. https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#events
There are only two requests to get a screenshot and save it to disk.

**Comment by DmitriySalnikov** [comment]
I have made a request to add this feature https://github.com/obsproject/obs-websocket/issues/1047

**Comment by DmitriySalnikov** [comment]
![image](https://user-images.githubusercontent.com/7782218/211499516-38667c00-c1a4-46bd-9812-79f876847ae7.png)
Now I need to update the library to interact with obs-websocket (the one I use at the moment does not have an official update yet) and update the OBS Notifier itself

**Comment by DmitriySalnikov** [comment]
Fixed in 8428ee69fc0f3643484e50e18fd98e868224fb2f
