### ISSUE TITLE
[Feature Request]: Closing Window Button . Visible in  Windows Processes ,  Tray App Exe

### ISSUE THREAD

**Issue by BodySame** [DmitriySalnikov/OBSNotifier#20]
### Feature description

Closing Window Button . Visible in  Windows Processes , Tray App Exe
Why Application Connect for Unknown Server When Choosen Localhost?

**Comment by DmitriySalnikov** [comment]
I don't understand what you want.

The program connects only to the specified address and remains in the tray until the `Exit` button is pressed. Or if the `Close this program when exiting OBS` setting is enabled, then this program will close along with OBS.

**Comment by BodySame** [comment]
Проясню по  нормальному.
Почему : программа не видна в системных процессах?
Второй : программа может выводить оверлеем nview или nvidia  чат в 3d  приложение?
Это доступно   при помощи cuda  кода   или rivatuner  api .Возможно  OBS

English 
 I'll explain it in a normal way.
Why: the program is not visible in system processes?
Second: can the program display nview or nvidia messages chat overlay in a 3d application?
This is available using cuda code or rivatuner api. Possibly OBS

**Comment by DmitriySalnikov** [comment]
> Почему : программа не видна в системных процессах?

Что значит в "системных процессах"? Программа отображается в диспетчере, как и все остальные. При этом остаётся в трее при закрытии окна настроек.

![image](https://github.com/user-attachments/assets/78e69341-7fd2-4422-8f8d-aeb1a14a524d)

Почему она не сервис? А зачем это нужно, если программа работает только в связке с OBS?

> Почему програма использует web extensions

Она работает через \*websocket интерфейс, который предоставляет доступ к событиям и статистике OBS.

> для вывода локального Nvidia сообщения.

Ничего от Nvidia тут нет, кроме похожего стиля.

> Есть другой метод irc.chat токены и шифрованая строка, способная выводить в текстовой файл любое сообщение чата и вести историю.

Совершенно не понимаю эту часть. IRC.chat это ведь буквально "чат", точнее площадка для создания self-hosted сообществ. Причём тут OBS?
Не, ну можно написать бота (плагин, прогу), который будет получать информацию о событиях от OBS и отправлять их в IRC/Telegram...

> И получать оповещения минуя интерфейс удаленного управления.

Для одного из типов оповещений будут использоваться логи. Но логи это ненадёжно, небыстро и неудобно.

> Второй : программа может выводить оверлеем nview или nvidia чат в 3d приложение?

`nView Desktop Manager`? Это вроде программа для управления виртуальными рабочими столами/экранами, а не оверлеями.
Что такое Nvidia чат?

> Это доступно при помощи cuda код

Зачем нужен CUDA код для вывода окошек я не понимаю.

> или rivatuner api

Вот про эту штуку я кстати забыл. Но во-первых для него есть API только на C++, во-вторых через него можно выводить ограниченный набор элементов, в основном это графики и текст, и в-третьих этот rivatuner тоже нужно держать открытым в фоне.

> English

Do I need to translate?

**Comment by DmitriySalnikov** [comment]
> Программа для оповещения в стрим чат. Уровень навыков - пользователь ПК.

Причём здесь оповещения в чат, если эта программа для человека, который записывает контент или ведёт стрим?

> проэкт

проект*

> Требует создания токена на твитче -уникальной строки для конкретного сайта или приложения.

То есть события OBS будут выводится в чат твича?..

> Весь web socket в OBS это по сути IRC

Ладно 😐

> CUDA выводит напрямую в 3d Render любого приложения.Пример кода
> https://forums.developer.nvidia.com/t/overlay-text/33115

Это пример OpenGL кода. Где тут CUDA?
Чтобы что-то рисовать поверх игры с использованием OpenGL или Vulkan обязательно требуется встраивание в процесс и получение его графического контекста.

Всё это выглядит как троллинг, а не реальный запрос на добавление фичи (возможно с применением GPT).

Либо объясните нормальным языком в следующем сообщении, чего вы хотите, либо я просто удалю эту страницу.

**Comment by BodySame** [comment]
> Причём здесь оповещения в чат, если эта программа для человека, который записывает контент или ведёт стрим?
Знаеш.Очень качественный программист.Я ошибся в этой строке. 
Это не программа оповещения в чат.
Это программа для оповещения чата. 

Исправляется заменой оповещения **в** чат на оповещения **из** чат
И да это *пример*...Мысленный эксперимент
И да в конце *сарказм*. 


Или по другому более четко  -  программа для  оповещения  сообщениями  из OBS  в необходимый источник.
Если проблемы в переводе я обьяснил.

> То есть события OBS будут выводится в чат твича?..
Да будут и ввводится тоже из твича..Получать их тоже можно оттуда.


> Где тут CUDA?
CUDA  это то где надо писать и что чтобы выводилось не используя сторонние программы - только драйвер видеокарты.

Поясню. Не каждый знает все программы и языки программирования на свете.


> Причём здесь оповещения в чат, если эта программа для человека, который записывает контент или ведёт стрим?
Знаеш.Очень качественный программист.Я ошибся в этой строке. 
Это не программа оповещения в чат.
Это программа для оповещения чата. 

Исправляется заменой оповещения **в** чат на оповещения **из** чат
И да это *пример*...Мысленный эксперимент
И да в конце *сарказм*. 


Или по другому более четко  -  программа для  оповещения  сообщениями  из OBS  в необходимый источник.
Если проблемы в переводе я обьяснил.

> То есть события OBS будут выводится в чат твича?..
Да будут и ввводится тоже из твича..Получать их тоже можно оттуда.


> Где тут CUDA?
CUDA  это то где надо   кодить  и что надо делать чтобы выводилось не используя сторонние программы - только драйвер видеокарты.

Поясню перфекционистам.
Я менеджер проекта, а не программист.
Я даю вам идеи – и не более того

Поясню. Не каждый знает все программы и языки программирования на свете.

What does this have to do with chat notifications if this program is for a person who records content or streams?

You know. A very high-quality programmer. I made a mistake in this line.
This is not a chat notification program.
This is a chat notification program. ( This is  from chat notification program).

Fixed by replacing the **to** chat alerts with **from** chat alerts
And yes, this is an *example*...A mental  experiment . Dream..
And yes at the end of line  *sarcasm* statement.


Or in another more clear way of Technical specifications explanation  - a program for **notifying messages from OBS to the required source**.
If there are problems in  English or Russian translation, I explained.

> That is, OBS events will be displayed in the Twitch chat?..

Yes, they will be displayed and also can be handled from any source from Twitch.. You can also receive them from any IRC program.


> Where is CUDA?

CUDA is What you need to write and what to do to output Notifications without using third-party programs - only the video card driver.

Let me explain. Not everyone knows every program and programming language in the world. CUDA ,OpenGL.

Let me explain to the perfectionists.
I am project manager  not a programmer.

I   give you ideas - and nothing more
