### ISSUE TITLE
Notifications & preview does not show up on second monitor

### ISSUE THREAD

**Issue by mikkelens** [DmitriySalnikov/OBSNotifier#3]
It is visible on my main screen ("\\\\.\DISPLAY1")...
![Screenshot 1 (set to display 1)](https://user-images.githubusercontent.com/31762830/199853410-5723b68c-6bd1-46c5-84d6-f2a66b3bbf7c.png)
...but not on the second ("\\\\.\DISPLAY2").
![Screenshot 2 (set to display 2)](https://user-images.githubusercontent.com/31762830/199853405-5ff9686c-dd77-4225-9372-fab86eb29cc1.png)
I even tried changing settings around (safe display off, positional offset etc), reset settings and made sure it still worked with screen 1 again. Not sure if my Windows is broken or something.
The second monitor being an odd ratio (16:10) or being set to vertical wouldn't break the notification visuals, right?
I tested with actual notifications too (switching scenes manually) and not just the preview, but no luck.

**Comment by mikkelens** [comment]
btw this program seems to work very nicely. I'm hoping I can get it working correctly :^)

**Comment by DmitriySalnikov** [comment]
I noticed a similar problem recently due to different screen resolutions.

theoretically, the notification could be here somewhere..
![image](https://user-images.githubusercontent.com/7782218/199855625-d8784b42-132a-4aa8-8cdc-78fa74cc5b97.png)

**Comment by DmitriySalnikov** [comment]
I found the reason, but I don't remember why I did it like this 😅

without factors, it works correctly for me
https://github.com/DmitriySalnikov/OBSNotifier/blob/1ee2b8ab9fc3d9d7422c55a297e5678dc244f225/OBSNotifier/WPFScreens.cs#L67-L76

there may be problems when changing the scale of the display

**Comment by DmitriySalnikov** [comment]
I am ready to publish this update.
Please check if the problem is solved.
[OBSNotifier.zip](https://github.com/DmitriySalnikov/OBSNotifier/files/9934855/OBSNotifier.zip)

**Comment by mikkelens** [comment]
It works!
I'm astounded you managed to fix it this early, thanks a lot.
I'll report back to this if there are any other issues.
