### ISSUE TITLE
[Feature Request]: Handle graceful termination signal

### ISSUE THREAD

**Issue by BenJuan26** [DmitriySalnikov/OBSNotifier#7]
### Feature description

First of all, this thing is great! It's pretty much exactly what I've been looking for.

As currently implemented, the program will close the running window if the window is open and `taskkill /pid [notifier-pid]` is run. However, it will keep running in the tray. If only the tray is running, it won't do anything with the signal at all.

I imagine this might be intentional. My use case is that I would like to control the termination of both OBS and the Notifier from a script. I can force-kill the processes, but I want to avoid that for two reasons: 1) I want both programs to do any cleanup they need to do, and 2) when they are forced to close, their icons remain in the system tray until mouseover. Of course the second one is not a big deal, but I don't want to open my system tray to find a bunch of dead icons there that have to be moused-over to get rid of them.

Also, not sure if this is relevant, but OBS will gracefully close with `taskkill`, even when it's running in the tray, as long as no recordings are enabled (if they are, it will prompt).

**Comment by DmitriySalnikov** [comment]
> As currently implemented, the program will close the running window if the window is open and `taskkill /pid [notifier-pid]` is run. However, it will keep running in the tray. If only the tray is running, it won't do anything with the signal at all.

I never even thought it could work like this 😅

> Also, not sure if this is relevant, but OBS will gracefully close with `taskkill`

Is it closing properly for sure? If yes, then this checkbox should also work correctly.
![image](https://user-images.githubusercontent.com/7782218/235348410-61c072cd-81e3-4ce9-9bff-8997d734c22e.png)

---

I checked it and the checkbox doesn't work. This means that `obs-websocket` does not have time to send a signal to close obs or simply ignores it.

---

I have tested several ways, but none of them responds to taskkill. I even installed Microsoft.Extensions (+30 libraries...) and nothing worked either.
![image](https://user-images.githubusercontent.com/7782218/235349956-f8021578-fb2c-45fd-a09d-1eecabcb5e27.png)

But on the other hand, I found that the application responds to 4 taskkills in a row 👍
Probably in .NET 5 it could work, but I can't port this application to it.

**Comment by BenJuan26** [comment]
Ok, this is interesting. It seems that when I taskkill OBS, it turns out that 90% of the time, it does indeed close OBSNotifier. So I can probably get away with using the start script and ticking the box to close it with OBS, and do `taskkill /f /im OBSNotifier.exe` from my script to kill any remaining instances.

But, all that being said, it appears that even gracefully killing OBS doesn't always clean up the icons 😢 So I might just be better off controlling the whole program flow from my script.

Feel free to close this, since according to what you tried, it's not feasible to implement anyway.

**Comment by DmitriySalnikov** [comment]
I've been thinking that maybe it's worth adding something like `obsnotifier.exe --kill`?
This command will be able to return `errorlevel` (exit code) 0 or an error if another copy of the program is not running or after a timeout of 5 seconds.
And after this command, do a forced `taskkill` if necessary.
