### ISSUE TITLE
In install documentation state where can you find custom_libs folder

### ISSUE THREAD

**Issue by tomasz-brak** [DmitriySalnikov/OBSNotifier#8]
While installing the program i was not able to find obs-websocket.dll the custom_libs folder mentioned in the last part of install documentation does not say where it is located.

**Comment by DmitriySalnikov** [comment]
Do you mean this [article](https://dmitriysalnikov.itch.io/obs-notifier/devlog/335353/how-to-install-obs-notifier-491-and-491-compat)? If so, it states that for older versions you need to use OBS Notifier [1.0.5](https://github.com/DmitriySalnikov/OBSNotifier/releases/tag/1.0.5) or older ([1.0.4](https://github.com/DmitriySalnikov/OBSNotifier/releases/tag/1.0.4), 1.0.3..).

For new versions of OBS, no additional actions are required, so there is no `custom_libs`.
